<?php 

// DATABASE CONOFIGURATION
define('DB_HOST','YOUR DB_HOST HERE');
define('DB_PORT','YOUR DB_HOST HERE');
define('DB_NAME','YOUR DB_NAME HERE');
define('DB_USER','YOUR DB_HOST HERE');
define('DB_PASS','YOUR DB_HOST HERE');